package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.LinkedList;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.Pane;

public class MainFormController {
	@FXML
	private Pane addOrderPanel;
	@FXML
	private Button addOrderButton;
	@FXML
	private ComboBox itemComboBox;
	@FXML
	private ComboBox updateItemComboBox;
	@FXML
	private TextField qtyTextBox;
	@FXML
	private Label itemsInOrderLabel;

	
	@FXML
	private Pane updatePricePanel;
	@FXML
	private Pane salesReportPanel;
	@FXML
	private Label salesReportLabel;
	@FXML
	private TextField currentPriceTextField;
	@FXML
	private Button updatePriceButton;
	@FXML
	private Label statusLabel;
	@FXML
	private Label updatePriceStatusLabel;

	Restaurant restaurant ;
	Order  activeOrder;
	private LinkedList<FoodItem> items = new LinkedList<FoodItem>();
	
	
	
	// Event Listener on Button.onAction
	@FXML
	public void showOrderForm(ActionEvent event) {
		salesReportPanel.setVisible(false);
		addOrderPanel.setVisible(true);
		updatePricePanel.setVisible(false);
		
		restaurant = new Restaurant("BurritoKing");
		activeOrder = new Order();
		statusLabel.setText("");
		items = new LinkedList<FoodItem>();
		//showOrderCount();

		items.add(new Burrito(Restaurant.getPrice("Burrito"), 1));
		items.add(new Fries(Restaurant.getPrice("Fries"), 1));
		items.add(new Soda(Restaurant.getPrice("Soda"), 1));
		//items.add(new Soda(Restaurant.getPrice("Meal"), 1));

		itemComboBox.getItems().clear();
		itemComboBox.getItems().addAll(items);
		itemComboBox.getSelectionModel().select(new Burrito(Restaurant.getPrice("Burrito"), 1));
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void salesReportButtonClick(ActionEvent event) {
		salesReportPanel.setVisible(true);
		addOrderPanel.setVisible(false);
		updatePricePanel.setVisible(false);
	}
	// Event Listener on Button.onAction
	@FXML
	public void updatePriceButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void updatePriceMenuButtonClick(ActionEvent event) {
		salesReportPanel.setVisible(false);
		addOrderPanel.setVisible(false);
		updatePricePanel.setVisible(true);
	}
	
	// Event Listener on Button[#addOrderButton].onAction
	@FXML
	public void addItemButtonClick(ActionEvent event) {
		if (itemComboBox.getValue() != null) {
			
			String itemQty = qtyTextBox.getText();
			FoodItem selectedItem =(FoodItem) itemComboBox.getValue();
			int qty = 0;
					
			try {
				qty = Integer.valueOf(itemQty);
			} catch (Exception e) {
				qty = 0;
			}
			
			if (qty > 0) {
				int quantity = qty;
				selectedItem.addQuantity(quantity);
				this.activeOrder.addFoodItem(selectedItem);
				statusLabel.setText("Order updated");
			}else {
				statusLabel.setText("Please enter valid quantity");
			}
		}else {
			statusLabel.setText("Please select item first");
		}
	}
	
}
